DROP TABLE IF EXISTS post_views;
CREATE TABLE post_views (
  slug TEXT PRIMARY KEY,
  views INTEGER DEFAULT 0
);

DROP TABLE IF EXISTS post_likes;
CREATE TABLE post_likes (
  slug TEXT PRIMARY KEY,
  likes INTEGER DEFAULT 0
);

DROP TABLE IF EXISTS comments;
CREATE TABLE comments (
  id TEXT PRIMARY KEY,
  slug TEXT NOT NULL,
  content TEXT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
