import type { Metadata } from "next";
import localFont from "next/font/local";
import TrpcProvider from '@/lib/trpc/Provider';
import { ClerkProvider } from '@clerk/nextjs';
import { Inter } from 'next/font/google';
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import "../globals.css";
import { zhCN } from "@clerk/localizations";
import { Navbar } from "@/components/layout/Navbar";
import { Footer } from "@/components/layout/Footer";
import { ThemeProvider } from "@/components/core/ThemeProvider";

const geistSans = localFont({
    src: "../fonts/GeistVF.woff",
    variable: "--font-geist-sans",
});
const geistMono = localFont({
    src: "../fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const inter = Inter({ subsets: ['latin'] });

export default async function RootLayout({
    children,
    params
}: {
    children: React.ReactNode;
    params: Promise<{ locale: string }>;
}) {
    const { locale } = await params;
    const messages = await getMessages();

    return (
        <ClerkProvider localization={zhCN}>
            <html lang={locale} suppressHydrationWarning>
                <body className={`${geistSans.variable} ${geistMono.variable}`}>
                    <NextIntlClientProvider messages={messages}>
                        <TrpcProvider>
                            <ThemeProvider attribute="data-theme" defaultTheme="dark" enableSystem>
                                <Navbar />
                                <main style={{ minHeight: '100vh', paddingTop: 'var(--header-height)' }}>
                                    {children}
                                </main>
                                <Footer />
                            </ThemeProvider>
                        </TrpcProvider>
                    </NextIntlClientProvider>
                </body>
            </html>
        </ClerkProvider>
    );
}
