import type { Metadata } from "next";
import localFont from "next/font/local";
import TrpcProvider from '@/lib/trpc/Provider';
import { Inter } from 'next/font/google';
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import "../globals.css";
import { Navbar } from "@/components/layout/Navbar";
import { Footer } from "@/components/layout/Footer";
import { ThemeProvider } from "@/components/core/ThemeProvider";
import { HOLIDAY_CONFIG } from "@/lib/config/holiday";
import Snowfall from "@/components/core/Snowfall";

const geistSans = localFont({
    src: "../fonts/GeistVF.woff",
    variable: "--font-geist-sans",
});
const geistMono = localFont({
    src: "../fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
});

export const metadata: Metadata = {
    title: "Vist Blog",
    description: "Generated by Vist Blog",
};

const inter = Inter({ subsets: ['latin'] });

export function generateStaticParams() {
    return [{ locale: 'en' }, { locale: 'zh' }];
}

export default async function RootLayout({
    children,
    params
}: {
    children: React.ReactNode;
    params: Promise<{ locale: string }>;
}) {
    const { locale } = await params;
    const messages = await getMessages();

    return (
        <html lang={locale} suppressHydrationWarning>
            <head>
                <script
                    dangerouslySetInnerHTML={{
                        __html: `
              if (typeof window !== 'undefined' && !window.__name) {
                Object.defineProperty(window, '__name', {
                  writable: true,
                  enumerable: false,
                  configurable: true,
                  value: function(func) {
                    return (func && func.displayName) || (func && func.name) || '';
                  }
                });
              }
            `,
                    }}
                />
            </head>
            <body className={`${geistSans.variable} ${geistMono.variable} ${HOLIDAY_CONFIG.isChristmas ? 'christmas-theme' : ''}`}>
                <NextIntlClientProvider messages={messages}>
                    <TrpcProvider>
                        <ThemeProvider attribute="data-theme" defaultTheme="dark" enableSystem>
                            {HOLIDAY_CONFIG.isChristmas && <Snowfall />}
                            <Navbar />
                            <main style={{ minHeight: '100vh', paddingTop: 'var(--header-height)' }}>
                                {children}
                            </main>
                            <Footer />
                        </ThemeProvider>
                    </TrpcProvider>
                </NextIntlClientProvider>
            </body>
        </html>
    );
}
